library(readr)
library(dplyr)
alumni <- read_csv(file.path("data","raw","alumni_engagement_raw.csv"), show_col_types=FALSE)
cat("\n=== DATA QUALITY CHECK ===\n")
cat("Rows:", nrow(alumni), "\n")
cat("Columns:", ncol(alumni), "\n")
cat("\nData types:\n")
print(sapply(alumni, class))
cat("\nMissing values by column:\n")
print(sapply(alumni, function(x) sum(is.na(x))))
cat("\nDuplicate Alumni_ID values:\n")
print(alumni %>% count(Alumni_ID) %>% filter(n > 1))
cat("\nUnique Branch values:\n")
print(sort(unique(alumni$Branch)))
cat("\nUnique Mentorship values:\n")
print(sort(unique(alumni$Mentorship)))
cat("\nUnique Batch values:\n")
print(sort(unique(alumni$Batch)))
cat("\nNumeric summary:\n")
print(summary(alumni %>% select(Graduation_Year, Event_Attendance, Email_Response, Donations, Networking_Events, Alumni_Meetings)))
